### ISSUE TITLE
Crash with searchable tableview in 0.7-head

### ISSUE THREAD

**Issue by markrickert** [infinitered/ProMotion#104]
I've got a table that works fine in `0.6` and when I tap the search box to begin searching, the app crashes in `version-0.7`.

The initial table loads correctly and it only crashes if you tap the search field.

``` bash
(main)> 2013-05-30 12:11:49.693 BA Styles[92849:c07] _table.rb:104:in `tableView:cellForRowAtIndexPath:': undefined method `table_view_cell' for true:TrueClass (NoMethodError)
2013-05-30 12:11:49.694 BA Styles[92849:c07] *** Terminating app due to uncaught exception 'NoMethodError', reason: '_table.rb:104:in `tableView:cellForRowAtIndexPath:': undefined method `table_view_cell' for true:TrueClass (NoMethodError)
'
*** First throw call stack:
(0x1cd8012 0x7bae7e 0x339a44 0x3f52 0x3591)
libc++abi.dylib: terminate called throwing an exception
((null))> rake aborted!
Command failed with status (1): [DYLD_FRAMEWORK_PATH="/Applications/Xcode.a...]
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `call'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `sh'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/file_utils_ext.rb:37:in `sh'
/Library/RubyMotion/lib/motion/project/template/ios.rb:93:in `block in <top (required)>'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/task.rb:205:in `block in invoke_prerequisites'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/task.rb:183:in `block in invoke_with_call_chain'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/bin/ruby_noexec_wrapper:14:in `eval'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => default => simulator
(See full trace by running task with --trace)
```
