### ISSUE TITLE
ProMotion 1.2.1 update to 2.0.0 - Unable to pass data to PM::FormotionScreen

### ISSUE THREAD

**Issue by PeterBloom** [infinitered/ProMotion#519]
I just updated to ProMotion 2.0.0 and I am getting some broken behavior regarding assessors and passed data to a PM::FormotionScreen. (This was working fine in ProMotion 1.2.1).

In my app, (1) I seed a @user in AppDelegate, and (2) can pass it to a LandingScreen like so,

def on_load(app, options)
seed_user(request_endpoint)
open LandingScreen.new(nav_bar: true, user: @user)
end

I can see the user object with puts in AppDelegate and on the LandingScreen, so I know it passed correctly. From the LandingScreen, I then open a SignInScreen which is a PM::FormotionScreen. I try to pass the user object like so,

``` ruby
open SignInScreen.new(nav_bar: true, user: user)
```

On the SignInScreen, I have,

``` ruby
attr_accessor :user

def table_data
{sections: [{
rows: [{
title: "User Name",
type: :string,
placeholder: "name",
value: "#{user.name}",
key: :name,
input_accessory: :done
}]
}, {
rows: [{
title: "Sign In",
type: :submit,
}]
}]
}
```

When the table_data is called I get the error

```
sign_in_screen.rb:36:in table_data': undefined method 'name' for nil:NilClass (NoMethodError)
from formotion_screen.rb:11:in `new:'
```

So, the user object is not there (nil). What’s happening?
